//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManege
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Quantity { get; set; }
        public int IDHeader { get; set; }
        public string Posion { get; set; }
    
        public virtual Header Header { get; set; }
        public virtual Borrow Borrow { get; set; }
    }
}
