//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManege
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int IDReader { get; set; }
        public int IDBook { get; set; }
        public int IDLibrarian { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime ExpertDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
